site_name: segment-geospatial

site_url: https://samgeo.gishub.org

repo_url: https://github.com/opengeos/segment-geospatial

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          execute: False
          ignore_h1_titles: True
          #   execute_ignore: "*.ipynb"

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/opengeos/segment-geospatial/issues
    - Examples:
          - examples/satellite.ipynb
          - examples/satellite-predictor.ipynb
          - examples/automatic_mask_generator.ipynb
          - examples/input_prompts.ipynb
    - API Reference:
          - common module: common.md
          - samgeo module: samgeo.md
